modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fastspawner"
version = "${version}"
displayName = "FastSpawner"
authors = "Kall"
description = '''
'''
#logoFile = ""